# Generated by Django 2.2.2 on 2019-06-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maquiagem_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maquiagem',
            old_name='Descricao',
            new_name='descricao',
        ),
    ]
