# Generated by Django 2.2.1 on 2019-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190630_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquiagem',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor'),
        ),
    ]
